version: '3.8'

services:
  db:
    image: postgres:15
    container_name: todo_postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: securepassword
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U todo_user -d todo_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: todo_django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://todo_user:securepassword@db:5432/todo_db

  frontend:
    build: ./frontend
    container_name: todo_frontend
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      backend:
        condition: service_started
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
    environment:
      REACT_APP_BACKEND_URL: "http://localhost:8000"

volumes:
  postgres_data:
  frontend_node_modules:
